// Code generated by MockGen. DO NOT EDIT.
// Source: position_repo.go
//
// Generated by this command:
//
//	mockgen -source=position_repo.go -destination=mock_position_repo.go -package=repo
//

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"

	model "github.com/Yogdunana/StarByte/backend/internal/rbac/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPositionRepo is a mock of PositionRepo interface.
type MockPositionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPositionRepoMockRecorder
}

// MockPositionRepoMockRecorder is the mock recorder for MockPositionRepo.
type MockPositionRepoMockRecorder struct {
	mock *MockPositionRepo
}

// NewMockPositionRepo creates a new mock instance.
func NewMockPositionRepo(ctrl *gomock.Controller) *MockPositionRepo {
	mock := &MockPositionRepo{ctrl: ctrl}
	mock.recorder = &MockPositionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPositionRepo) EXPECT() *MockPositionRepoMockRecorder {
	return m.recorder
}

// CountUsersByPositionID mocks base method.
func (m *MockPositionRepo) CountUsersByPositionID(ctx context.Context, tx *gorm.DB, positionID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsersByPositionID", ctx, tx, positionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsersByPositionID indicates an expected call of CountUsersByPositionID.
func (mr *MockPositionRepoMockRecorder) CountUsersByPositionID(ctx, tx, positionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsersByPositionID", reflect.TypeOf((*MockPositionRepo)(nil).CountUsersByPositionID), ctx, tx, positionID)
}

// Create mocks base method.
func (m *MockPositionRepo) Create(ctx context.Context, tx *gorm.DB, pos *model.Position) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, pos)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPositionRepoMockRecorder) Create(ctx, tx, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPositionRepo)(nil).Create), ctx, tx, pos)
}

// Delete mocks base method.
func (m *MockPositionRepo) Delete(ctx context.Context, tx *gorm.DB, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPositionRepoMockRecorder) Delete(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPositionRepo)(nil).Delete), ctx, tx, id)
}

// GetByCode mocks base method.
func (m *MockPositionRepo) GetByCode(ctx context.Context, code string) (*model.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*model.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockPositionRepoMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockPositionRepo)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockPositionRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPositionRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPositionRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPositionRepo) List(ctx context.Context, page, pageSize int, keyword string) ([]model.Position, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize, keyword)
	ret0, _ := ret[0].([]model.Position)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPositionRepoMockRecorder) List(ctx, page, pageSize, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPositionRepo)(nil).List), ctx, page, pageSize, keyword)
}

// Update mocks base method.
func (m *MockPositionRepo) Update(ctx context.Context, tx *gorm.DB, pos *model.Position) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, pos)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPositionRepoMockRecorder) Update(ctx, tx, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPositionRepo)(nil).Update), ctx, tx, pos)
}
