// Code generated by MockGen. DO NOT EDIT.
// Source: permission_repo.go
//
// Generated by this command:
//
//	mockgen -source=permission_repo.go -destination=mock_permission_repo.go -package=repo
//

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"

	model "github.com/Yogdunana/StarByte/backend/internal/rbac/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPermissionRepo is a mock of PermissionRepo interface.
type MockPermissionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepoMockRecorder
}

// MockPermissionRepoMockRecorder is the mock recorder for MockPermissionRepo.
type MockPermissionRepoMockRecorder struct {
	mock *MockPermissionRepo
}

// NewMockPermissionRepo creates a new mock instance.
func NewMockPermissionRepo(ctrl *gomock.Controller) *MockPermissionRepo {
	mock := &MockPermissionRepo{ctrl: ctrl}
	mock.recorder = &MockPermissionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepo) EXPECT() *MockPermissionRepoMockRecorder {
	return m.recorder
}

// CountChildren mocks base method.
func (m *MockPermissionRepo) CountChildren(ctx context.Context, parentID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountChildren", ctx, parentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountChildren indicates an expected call of CountChildren.
func (mr *MockPermissionRepoMockRecorder) CountChildren(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountChildren", reflect.TypeOf((*MockPermissionRepo)(nil).CountChildren), ctx, parentID)
}

// Create mocks base method.
func (m *MockPermissionRepo) Create(ctx context.Context, tx *gorm.DB, permission *model.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPermissionRepoMockRecorder) Create(ctx, tx, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionRepo)(nil).Create), ctx, tx, permission)
}

// Delete mocks base method.
func (m *MockPermissionRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPermissionRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPermissionRepo)(nil).Delete), ctx, id)
}

// GetByCode mocks base method.
func (m *MockPermissionRepo) GetByCode(ctx context.Context, code string) (*model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockPermissionRepoMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockPermissionRepo)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockPermissionRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPermissionRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPermissionRepo)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockPermissionRepo) GetByIDs(ctx context.Context, tx *gorm.DB, ids []uuid.UUID) ([]model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, tx, ids)
	ret0, _ := ret[0].([]model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockPermissionRepoMockRecorder) GetByIDs(ctx, tx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockPermissionRepo)(nil).GetByIDs), ctx, tx, ids)
}

// GetPermissionCodesByUserID mocks base method.
func (m *MockPermissionRepo) GetPermissionCodesByUserID(ctx context.Context, userID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionCodesByUserID", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionCodesByUserID indicates an expected call of GetPermissionCodesByUserID.
func (mr *MockPermissionRepoMockRecorder) GetPermissionCodesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionCodesByUserID", reflect.TypeOf((*MockPermissionRepo)(nil).GetPermissionCodesByUserID), ctx, userID)
}

// GetPermissionIDsByUserID mocks base method.
func (m *MockPermissionRepo) GetPermissionIDsByUserID(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionIDsByUserID", ctx, userID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionIDsByUserID indicates an expected call of GetPermissionIDsByUserID.
func (mr *MockPermissionRepoMockRecorder) GetPermissionIDsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionIDsByUserID", reflect.TypeOf((*MockPermissionRepo)(nil).GetPermissionIDsByUserID), ctx, userID)
}

// List mocks base method.
func (m *MockPermissionRepo) List(ctx context.Context) ([]model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPermissionRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPermissionRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockPermissionRepo) Update(ctx context.Context, tx *gorm.DB, permission *model.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPermissionRepoMockRecorder) Update(ctx, tx, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPermissionRepo)(nil).Update), ctx, tx, permission)
}
